name: Slack Webhook Handler

on:
  workflow_dispatch: # Allows manual triggering
  issue_comment: # Respond to issue comments (for testing)
  push:
    branches:
      - main

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run the Webhook Handler
        run: |
          echo "Handling Slack Webhook..."
          # You can add your webhook handling logic here
app.post('/slack/events', async (req, res) => {
  const { type, event } = req.body;

  if (type === 'url_verification') {
    return res.status(200).send(event.challenge);
  }

  // Handle the message event
  if (event && event.type === 'message' && !event.subtype) {
    const channelId = event.channel;
    const userId = event.user;
    const messageText = event.text;

    // Respond to the message
    await app.client.chat.postMessage({
      channel: channelId,
      text: `Hello <@${userId}>! You said: "${messageText}"`,
    });
  }

  res.status(200).send('Event received');
});
