const express = require("express");
const app = express();
app.use(express.json());  // To handle JSON payloads

// Route to handle Slack's challenge request
app.post("/slack/events", (req, res) => {
  if (req.body.challenge) {
    res.status(200).send(req.body.challenge);  // Respond with the challenge
  } else {
    res.status(400).send("No challenge found.");
  }
});

// Start the server
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
