name: Slack Webhook Handler

on:
  workflow_dispatch: # Allows manual triggering for testing
  issue_comment: # For testing purposes, responds to comments on issues

jobs:
  handle-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check for URL Verification Challenge
        if: github.event.issue.body == 'url_verification' # Simulate challenge response for testing
        run: |
          echo "Responding to URL verification challenge..."
          echo "Challenge: ${{ github.event.comment.body }}" # Simulated challenge response

      - name: Handle Slack Message Event
        if: github.event.action == 'created' && github.event.issue.title == 'slack-message' # Simulating a message event
        run: |
          echo "Handling Slack message event..."
          USER_ID="User"
          MESSAGE_TEXT="${{ github.event.comment.body }}" # Assuming comment body is the message text
          echo "Received message from $USER_ID: \"$MESSAGE_TEXT\""
          echo "Response: Hello @${USER_ID}, you said: \"$MESSAGE_TEXT\""
